name: Auto Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    env:
      DOTNET_INSTALL_DIR: ./.dotnet-sdk
      Build_Configuration: Release
      Build_Directory: ./bin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dotnet
        id: cache-dotnet
        uses: actions/cache@v4
        with:
          path: "${{ env.DOTNET_INSTALL_DIR }}"
          key: "${{ runner.os }}-dotnet"

      - name: Install dotnet
        if: steps.cache-dotnet.outputs.cache-hit != 'true'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run build
        run: |
          dotnet publish -c ${{ env.Build_Configuration }}

      # - name: Zip artifacts
      #   uses: thedoctor0/zip-release@0.7.6
      #   with:
      #     path: "${{ env.Build_Directory }}"
      #     filename: "${{ env.Build_Directory }}/${{ github.event.repository.name }}.zip"

      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: "V${{ github.run_number }}"
          tag: "V${{ github.run_number }}"
          artifacts: "${{ env.Build_Directory }}/**/publish/*.exe"
