name: Build Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_INSTALL_DIR: ./.dotnet-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # - name: Install MSVC
      #   uses: TheMrMilchmann/setup-msvc-dev@v3
      #   with:
      #     arch: x64
      #     sdk: "10.0.26100.0"

      - name: Run build
        run: |
          dotnet publish -c Release

      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: "V${{ github.run_number }}"
          tag: "V${{ github.run_number }}"
          artifacts: "./bin/*/Release/**/*.exe"

      # - name: Delete older releases
      #   uses: dev-drprasad/delete-older-releases@v0.3.4
      #   with:
      #     keep_latest: 10
      #     delete_tags: true

      # - name: Zip artifacts
      #   uses: thedoctor0/zip-release@0.7.6
      #   with:
      #     path: "./bin"
      #     filename: "${{ github.event.repository.name }}-V${{ github.run_number }}.zip"
